Repository Obyka/Teaching-HEIGVD-AMT-2019-Project-Two, pull requests merged in 2020-01, with the labels that each got.

#12 CRUD Pokemon
  project2-api-pokemon/spring-server/api-pokemon.iml
  project2-api-pokemon/spring-server/pom.xml
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/PokemonsApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/TrainersApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/exceptions/CaptureBadRequestException.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/exceptions/CaptureNotFoundException.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/exceptions/PokemonBadRequestException.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/exceptions/PokemonNotFoundException.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/exceptions/TrainerBadRequestException.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/exceptions/TrainerNotFoundException.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/entities/PokemonEntity.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/entities/TrainerEntity.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/repositories/PokemonRepository.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/repositories/TrainerRepository.java
  project2-api-pokemon/spring-server/src/main/resources/api-spec.yaml
  project2-api-pokemon/spring-server/src/main/resources/application.properties
Labels: TODO

#15 CRUD captures
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/CapturesApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/entities/CaptureEntity.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/repositories/CaptureRepository.java
  project2-api-pokemon/spring-server/src/main/resources/api-spec.yaml
Labels: Need review

#21 Fb api user
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/endpoints/LoginApiController.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/endpoints/PasswordApiController.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/endpoints/UsersApiController.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/exceptions/ForbiddenException.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/filters/AppConfig.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/filters/isAdminFilter.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/filters/isLoggedFilter.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/util/PasswordHash.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/util/UtilsJWT.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/entities/UserEntity.java
  project2-api-login/spring-server/src/main/resources/api-spec.yaml
Labels: Need review

#23 Link User API and Pokemon API
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/entities/UserEntity.java
  project2-api-pokemon/spring-server/api-pokemon.iml
  project2-api-pokemon/spring-server/pom.xml
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/CapturesApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/PokemonsApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/TrainersApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/exceptions/ForbiddenException.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/filters/AppConfig.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/filters/isLoggedFilter.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/util/UtilsJWT.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/entities/CaptureEntity.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/entities/PokemonEntity.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/entities/TrainerEntity.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/entities/UserEntity.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/repositories/CaptureRepository.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/repositories/PokemonRepository.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/repositories/TrainerRepository.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/repositories/UserRepository.java
  project2-api-pokemon/spring-server/src/main/resources/api-spec.yaml
Labels: Need review

#33 Fb to annotation
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/CapturesApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/PokemonsApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/TrainersApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/entities/CaptureEntity.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/repositories/CaptureRepository.java
  project2-api-pokemon/spring-server/src/main/resources/api-spec.yaml
  project2-api-pokemon/spring-server/src/main/resources/application.properties
Labels: Need review

#34 everything is PAGINATED
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/CapturesApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/PokemonsApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/TrainersApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/repositories/CaptureRepository.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/repositories/PokemonRepository.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/repositories/TrainerRepository.java
  project2-api-pokemon/spring-server/src/main/resources/api-spec.yaml
Labels: Closed

#35 Fix PUT requests
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/PokemonsApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/TrainersApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/entities/CaptureEntity.java
  project2-api-pokemon/spring-server/src/main/resources/api-spec.yaml
Labels: Need review

#22 Generated code for Cucumber tests
  project2-api-login/login-api-specs-test/.idea/.gitignore
  project2-api-login/login-api-specs-test/.idea/compiler.xml
  project2-api-login/login-api-specs-test/.idea/encodings.xml
  project2-api-login/login-api-specs-test/.idea/misc.xml
  project2-api-login/login-api-specs-test/.idea/vcs.xml
  project2-api-login/login-api-specs-test/pom.xml
  project2-api-login/login-api-specs-test/src/main/resources/api-spec.yaml
  project2-api-login/login-api-specs-test/src/test/java/ch/heig/amt/login/api/spec/SpecificationTest.java
  project2-api-login/login-api-specs-test/src/test/java/ch/heig/amt/login/api/spec/helpers/Environment.java
  project2-api-login/login-api-specs-test/src/test/java/ch/heig/amt/login/api/spec/steps/CreationSteps.java
  project2-api-login/login-api-specs-test/src/test/resources/environment.properties
  project2-api-login/login-api-specs-test/src/test/resources/scenarios/creation.feature
  project2-api-pokemon/pokemon-api-specs-test/.idea/.gitignore
  project2-api-pokemon/pokemon-api-specs-test/.idea/compiler.xml
  project2-api-pokemon/pokemon-api-specs-test/.idea/encodings.xml
  project2-api-pokemon/pokemon-api-specs-test/.idea/misc.xml
  project2-api-pokemon/pokemon-api-specs-test/.idea/vcs.xml
  project2-api-pokemon/pokemon-api-specs-test/pom.xml
  project2-api-pokemon/pokemon-api-specs-test/src/main/resources/api-spec.yaml
  project2-api-pokemon/pokemon-api-specs-test/src/test/java/ch/heig/amt/pokemon/api/spec/SpecificationTest.java
  project2-api-pokemon/pokemon-api-specs-test/src/test/java/ch/heig/amt/pokemon/api/spec/helpers/Environment.java
  project2-api-pokemon/pokemon-api-specs-test/src/test/java/ch/heig/amt/pokemon/api/spec/steps/CreationSteps.java
  project2-api-pokemon/pokemon-api-specs-test/src/test/resources/environment.properties
  project2-api-pokemon/pokemon-api-specs-test/src/test/resources/scenarios/creation.feature
Labels: Need review

#37 Cucumber tests for Login API
  docker/sql/create-login.sql
  project2-api-login/login-api-specs-test/pom.xml
  project2-api-login/login-api-specs-test/src/main/resources/api-spec.yaml
  project2-api-login/login-api-specs-test/src/test/java/ch/heig/amt/login/api/spec/helpers/Environment.java
  project2-api-login/login-api-specs-test/src/test/java/ch/heig/amt/login/api/spec/steps/CRUDoperationsSteps.java
  project2-api-login/login-api-specs-test/src/test/java/ch/heig/amt/login/api/spec/steps/CreationSteps.java
  project2-api-login/login-api-specs-test/src/test/java/ch/heig/amt/login/api/spec/steps/ErrorStatusCodeSteps.java
  project2-api-login/login-api-specs-test/src/test/java/ch/heig/amt/login/api/spec/steps/OthersScenariosSteps.java
  project2-api-login/login-api-specs-test/src/test/resources/environment.properties
  project2-api-login/login-api-specs-test/src/test/resources/scenarios/CRUDoperations.feature
  project2-api-login/login-api-specs-test/src/test/resources/scenarios/ErrorsStatusCode.feature
  project2-api-login/login-api-specs-test/src/test/resources/scenarios/OthersScenarios.feature
  project2-api-login/login-api-specs-test/src/test/resources/scenarios/creation.feature
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/endpoints/LoginApiController.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/endpoints/UsersApiController.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/exceptions/BadLoginException.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/exceptions/ForbiddenException.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/filters/isAdminFilter.java
  project2-api-login/spring-server/src/main/java/ch/heig/amt/login/api/filters/isLoggedFilter.java
  project2-api-login/spring-server/src/main/resources/application.properties
  project2-api-pokemon/spring-server/api-pokemon.iml
Labels: Need review

#39 Add some lines at beginning
  documentation/design-impl-api.md
Labels: Need review

#38 Fb cucumber tests pokemon api
  docker/sql/create-pokemon.sql
  project2-api-pokemon/pokemon-api-specs-test/pom.xml
  project2-api-pokemon/pokemon-api-specs-test/src/main/resources/api-spec.yaml
  project2-api-pokemon/pokemon-api-specs-test/src/test/java/ch/heig/amt/pokemon/api/spec/helpers/Environment.java
  project2-api-pokemon/pokemon-api-specs-test/src/test/java/ch/heig/amt/pokemon/api/spec/steps/CapturesScenariosSteps.java
  project2-api-pokemon/pokemon-api-specs-test/src/test/java/ch/heig/amt/pokemon/api/spec/steps/CreationSteps.java
  project2-api-pokemon/pokemon-api-specs-test/src/test/java/ch/heig/amt/pokemon/api/spec/steps/OthersScenariosSteps.java
  project2-api-pokemon/pokemon-api-specs-test/src/test/java/ch/heig/amt/pokemon/api/spec/steps/PokemonsScenariosSteps.java
  project2-api-pokemon/pokemon-api-specs-test/src/test/java/ch/heig/amt/pokemon/api/spec/steps/TrainersScenariosSteps.java
  project2-api-pokemon/pokemon-api-specs-test/src/test/resources/environment.properties
  project2-api-pokemon/pokemon-api-specs-test/src/test/resources/scenarios/CapturesScenarios.feature
  project2-api-pokemon/pokemon-api-specs-test/src/test/resources/scenarios/OthersScenarios.feature
  project2-api-pokemon/pokemon-api-specs-test/src/test/resources/scenarios/PokemonsScenarios.feature
  project2-api-pokemon/pokemon-api-specs-test/src/test/resources/scenarios/TrainersScenarios.feature
  project2-api-pokemon/pokemon-api-specs-test/src/test/resources/scenarios/creation.feature
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/endpoints/CapturesApiControllers.java
  project2-api-pokemon/spring-server/src/main/java/ch/heig/amt/pokemon/api/filters/isLoggedFilter.java
  project2-api-pokemon/spring-server/src/main/resources/api-spec.yaml
  project2-api-pokemon/spring-server/src/main/resources/application.properties
Labels: Need review

#40 Add new docs for Cucumber and bugs
  documentation/bugs-limitations.md
  documentation/cucumber_testing.md
Labels: Need review

#41 Update bugs-limitations.md
  documentation/bugs-limitations.md
Labels: Need review

#42 Implement script to launch test
  test.sh
Labels: Need review
